brew 'zplug'
brew 'peco'
brew 'rbenv'
brew 'ruby-build'
brew 'imagemagick'
brew 'git'
brew 'jq'
brew 'tig'
brew 'tree'
brew 'the_silver_searcher'
brew 'gibo'
brew 'nodebrew'
brew 'zsh-completions'
brew 'curl'
brew 'source-highlight'
brew 'ffmpeg'
brew 'gifsicle'
brew 'redis'
brew 'terminal-notifier'
brew 'hg'
brew 'gh'
brew 'ghq'
brew 'pyenv'
brew 'eza'

# GUI Apps
cask 'MonitorControl'
cask 'iterm2'
cask 'visual-studio-code'
cask 'google-chrome'
cask 'slack'
cask 'discord'
cask 'contexts'
cask 'provisionql'
cask 'clipy'
cask 'emacs'
cask 'karabiner-elements'
cask 'vivaldi'
cask 'xcodes'

# Fonts
tap 'homebrew/cask-fonts'
cask 'font-hackgen'
cask 'font-hackgen-nerd'

# Mac App Store
mas 'BetterSnapTool', id: 417375580
